### ISSUE TITLE
数学是正常的，但不习惯

### ISSUE THREAD

**Issue by erherhh4herh** [imnotanderson/JMath#1]
抱歉对不起中国，不过我想问一下为什么你在system.math上使用的数学库不好，没有扩展名。 谢谢您的回答！ 请使用自定义的数学函数而不是system.math感谢

**Comment by imnotanderson** [comment]
sorry,. i dont know whats your mean.. you can issue in english.
its your mean that why import System.Math?
because i just want to realize deterministic,
now this repo just use System.Math.Abs and System.Math.Sqrt
i will remove System.Math in my plan.

**Comment by imnotanderson** [comment]
System.Mathf has been removed.
